import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";

import "../../globals.css";
import Navbar from "../components/navbar";
import CompanyLogos from "../components/company-logos";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flysha - Website booking ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}text-white font-poppins bg-flysha-black`}
      >
        <section
          id="Signup"
          className="bg-[url('/assets/images/background/FLIGHT3.jpg')] bg-no-repeat bg-cover bg-left-top -z-10 min-h-screen"
        >
          <div className="Header-content bg-gradient-to-r from-[#080318] to-[rgba(8,3,24,0)] z=0 min-h-screen">
            {/* For Navbar */}
            <Navbar />
            <div className="flex flex-col justify-between min-h-[calc(100vh-78px)]">
              {children}
              {/* For Company Logo */}
              <CompanyLogos />
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
